site_name: 黒鳥のメモ

theme:
    name: material
extra:
    search:
        language: 'ja'

extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/custom.css"